---
- name: Create 10 nginx containers on all servers for load balancing
  hosts: all
  tasks:
    - name: Create 10 nginx container
      docker_container:
        image: nginx
        name: "container{{item}}"
      with_sequence: count=10
